### ISSUE TITLE
Can you help me out understanding what going on here?

### ISSUE THREAD

**Issue by BlueSkyDefender** [brimson/reshaders#1]
https://github.com/Brimson/libcargc/blob/4e47c977db997e0e2b2ba130b77f68d58b47f75a/shaders/cMotionBlur.fx#L210

Have a hard time understanding why you are adding a checkerboard pattern to your mix() of current flow and  past flow.
Can you explain what's going on here and why it works?

**Comment by Brimson** [comment]
Lerp is like this
lerp(x, y, s) = x + ((x - y) * s)

For this shader, it's
pFlow + ((pFlow - oFlow[0]) * uInterpolation * uPos) - this might be incorrect way to frame blend flow xD

uPos basically validates the S factor in the checker pattern. The pattern returns the uInterpolate if 1, zero regarless of value if 0

**Comment by brimson** [comment]
🐛
